# Site settings
title: Poetics of Politics
email: pop2017@posteo.at
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/pop-2017" # the subpath of your site, e.g. /blog/
url: "https://supergraph.github.io"
#twitter_username: jekyllrb
github_username:  supergraph

# Build settings
markdown: kramdown
